//@ts-check
import { select } from "../utils/random";

export default () => select(jobs)[0];
// I extracted this from chancejs and added a couple more jobs.
// I also removed some that didn't make sense to me

//List source: http://answers.google.com/answers/threadview/id/589312.html
const jobs = [
  "Account Executive",
  "Accountant",
  "Acquisition Analyst",
  "Acrobat",
  "Actor",
  "Actuary",
  "Administrative Analyst",
  "Administrative Asst.",
  "Administrator",
  "Advertising Director",
  "Aerospace Engineer",
  "Agent",
  "Agricultural Inspector",
  "Agricultural Scientist",
  "Air Traffic Controller",
  "Airline Pilot",
  "Animal Trainer",
  "Anthropologist",
  "Appraiser",
  "Architect",
  "Art Director",
  "Artist",
  "Astronaut",
  "Astronomer",
  "Athlete",
  "Athletic Coach",
  "Auditor",
  "Author",
  "Baker",
  "Ballet dancer",
  "Banker",
  "Bankruptcy Attorney",
  "Barber",
  "Bartender",
  "Benefits Manager",
  "Bio-feedback Specialist",
  "Biologist",
  "Biomedical Engineer",
  "Biotechnical Researcher",
  "Botanist",
  "Broadcaster",
  "Broker",
  "Building Contractor",
  "Building Inspector",
  "Building Manager",
  "Business Analyst",
  "Business Manager",
  "Business Planner",
  "Business owner",
  "Call Center Manager",
  "Cameraman",
  "Career Counselor",
  "Carpenter",
  "Cash Manager",
  "Ceramic Engineer",
  "Chef",
  "Chemical Engineer",
  "Chemist",
  "Chief Executive Officer",
  "Chief Information Officer",
  "Chief Medical Officer",
  "Chief Operation Officer",
  "Chief Technology Officer",
  "Child Care Manager",
  "Chiropractor",
  "Cinematographer",
  "City Housing Manager",
  "City Manager",
  "Civil Engineer",
  "Claims Manager",
  "Clergy",
  "Clinical Research Assistant",
  "Clown",
  "Coach",
  "Collections Manager",
  "Commercial Artist",
  "Communications Affairs Director",
  "Communications Director",
  "Communications Engineer",
  "Compensation Analyst",
  "Compliance Manager",
  "Comptroller",
  "Computer Engineer",
  "Computer Graphics Specialist",
  "Computer Manager",
  "Computer Operator",
  "Computer Ops. Manager",
  "Computer Programmer",
  "Computer engineer",
  "Construction Engineer",
  "Construction Manager",
  "Construction Worker",
  "Consultant",
  "Consumer Relations Manager",
  "Contract Administrator",
  "Copyright Attorney",
  "Copywriter",
  "Corporate Planner",
  "Corrections Officer",
  "Cosmetologist",
  "Counsellor",
  "Credit Analyst",
  "Cruise Director",
  "Cryptologist",
  "Customer Service Manager",
  "Dancer",
  "Data Security Manager",
  "Database Manager",
  "Day Care Instructor",
  "Dental Hygiene",
  "Dentist",
  "Design Engineer",
  "Designer",
  "Desktop Publisher",
  "Detective",
  "Developer",
  "Development Officer",
  "Diamond Merchant",
  "Dietitian",
  "Direct Marketer",
  "Director",
  "Dishwasher",
  "Distribution Manager",
  "Diversity Manager",
  "Doctor",
  "Driver",
  "EEO Compliance Manager",
  "Economist",
  "Editor",
  "Education Adminator",
  "Electrical Engineer",
  "Electro Optical Engineer",
  "Electronics Engineer",
  "Embassy Management",
  "Employment Agent",
  "Engineer",
  "Engineer Technician",
  "Engraver",
  "Entrepreneur",
  "Environmental Analyst",
  "Environmental Attorney",
  "Environmental Engineer",
  "Environmental Specialist",
  "Escrow Officer",
  "Estimator",
  "Executive Assistant",
  "Executive Director",
  "Executive Recruiter",
  "Facilities Manager",
  "Family Counselor",
  "Farmer",
  "Fashion Events Manager",
  "Fashion Merchandiser",
  "Fashion designer",
  "Fast Food Manager",
  "Film Producer",
  "Film Production Assistant",
  "Financial Analyst",
  "Financial Planner",
  "Financier",
  "Fine Artist",
  "Firefighter",
  "Fisherman",
  "Fitness Consultant",
  "Flight Attendant",
  "Flight Engineer",
  "Floral Designer",
  "Florist",
  "Food & Beverage Director",
  "Food Service Manager",
  "Forestry Technician",
  "Franchise Management",
  "Franchise Sales",
  "Fraud Investigator",
  "Freelance Writer",
  "Fund Raiser",
  "Funeral director",
  "Gardener",
  "General Counsel",
  "General Manager",
  "Geologist",
  "Geriatric Specialist",
  "Gerontologist",
  "Glamour Photographer",
  "Golf Club Manager",
  "Gourmet Chef",
  "Graphic Designer",
  "Grounds Keeper",
  "Hair stylist",
  "Hazardous Waste Manager",
  "Health Care Manager",
  "Health Service Administrator",
  "Health Therapist",
  "Hearing Officer",
  "Historian",
  "Home Economist",
  "Horticulturist",
  "Hospital Administrator",
  "Hotel Manager",
  "Human Resources Manager",
  "IT Architect",
  "IT Project Manager",
  "IT Systems Analyst",
  "Importer",
  "Industrial Designer",
  "Industrial Engineer",
  "Information Director",
  "Inside Sales",
  "Insurance Adjuster",
  "Interior Decorator",
  "Interior designer",
  "Internal Controls Director",
  "International Acct.",
  "International Courier",
  "International Lawyer",
  "Interpreter",
  "Investigator",
  "Investment Banker",
  "Investment Manager",
  "Janitor",
  "Jeweler",
  "Joint Venture Manager",
  "Journalist",
  "Judge",
  "Lab Services Director",
  "Lab Technician",
  "Labor Negotiator",
  "Labor Organizer",
  "Labor Relations Manager",
  "Land Developer",
  "Landscape Architect",
  "Landscapper",
  "Law Enforcement Officer",
  "Lawyer",
  "Lead Software Engineer",
  "Lead Software Test Engineer",
  "Leasing Manager",
  "Lecturer",
  "Legal Secretary",
  "Librarian",
  "Library Manager",
  "Licensed Practicing Nurse",
  "Life-guard",
  "Linguist",
  "Litigation Attorney",
  "Loan Officer",
  "Lobbyist",
  "Locksmith",
  "Logistics Manager",
  "MIS Manager",
  "Maid",
  "Maintenance Manager",
  "Makeup artist",
  "Managed Care Director",
  "Management Consultant",
  "Manager",
  "Managing Partner",
  "Manpower Planner",
  "Manufacturing Director",
  "Marine Biologist",
  "Market Res. Analyst",
  "Marketer",
  "Marketing Director",
  "Materials Manager",
  "Mathematician",
  "Mechanic",
  "Mechanical Engineer",
  "Media Buyer",
  "Medical Assistant",
  "Medical Investor",
  "Medical Secretary",
  "Medical Specialist",
  "Medical Technician",
  "Membership Chairman",
  "Mental Health Counselor",
  "Merchandiser",
  "Metallurgical Engineering",
  "Meteorologist",
  "Microbiologist",
  "Midwife",
  "Miner",
  "Model",
  "Mortician",
  "Motion Picture Director",
  "Multimedia Director",
  "Musician",
  "Nanny",
  "Network Administrator",
  "Network Operator",
  "Network Specialist",
  "New Product Manager",
  "Novelist",
  "Nuclear Engineer",
  "Nuclear Specialist",
  "Nursing Administrator",
  "Nutritionist",
  "Occupational Therapist",
  "Oceanographer",
  "Office Manager",
  "Office clerk",
  "Office temp",
  "Operations Manager",
  "Operations Research Director",
  "Optical Technician",
  "Optometrist",
  "Organizational Development Manager",
  "Outplacement Specialist",
  "PR Specialist",
  "Painter",
  "Paleontologist",
  "Paralegal",
  "Paramedic",
  "Park Ranger",
  "Patent Attorney",
  "Payroll Specialist",
  "Personnel Specialist",
  "Petroleum Engineer",
  "Pharmacist",
  "Photographer",
  "Physical Therapist",
  "Physician",
  "Physician Assistant",
  "Physicist",
  "Planning Director",
  "Plumber",
  "Podiatrist",
  "Poet",
  "Police",
  "Political Analyst",
  "Political Scientist",
  "Politician",
  "Pool cleaner",
  "Portfolio Manager",
  "Postman",
  "Preschool Management",
  "Preschool Teacher",
  "Principal",
  "Private Banker",
  "Private Investigator",
  "Probation Officer",
  "Process Engineer",
  "Producer",
  "Product Engineer",
  "Product Manager",
  "Production Engineer",
  "Production Planner",
  "Professional Athlete",
  "Professional Coach",
  "Professional gamer",
  "Professional poker player",
  "Professor",
  "Program Manager",
  "Project Engineer",
  "Project Manager",
  "Property Manager",
  "Psychiatrist",
  "Psychologist",
  "Public Administrator",
  "Public Safety Director",
  "Public safety officer",
  "Publisher",
  "Publishing Director",
  "Purchasing Agent",
  "Quality Assurance Specialist",
  "Quality Control Engineer",
  "Quality Control Inspector",
  "Radiology Manager",
  "Railroad Engineer",
  "Real Estate Broker",
  "Real estate agent",
  "Recreational Director",
  "Recruiter",
  "Redevelopment Specialist",
  "Referee",
  "Registered Nurse",
  "Regulatory Affairs Manager",
  "Rehabilitation Counselor",
  "Relocation Manager",
  "Reporter",
  "Research Specialist",
  "Researcher",
  "Restaurant Manager",
  "Retail Store Manager",
  "Risk Analyst",
  "Safety Engineer",
  "Sailor",
  "Sales Engineer",
  "Sales Manager",
  "Sales Promotion Manager",
  "Sales Representative",
  "Sales Trainer",
  "Sales rep",
  "Sanitation Engineer",
  "Scientific Programmer",
  "Scientific Writer",
  "Securities Analyst",
  "Security Consultant",
  "Security Director",
  "Security guard",
  "Seminar Presenter",
  "Service Manager",
  "Ship's Officer",
  "Singer",
  "Social Director",
  "Social Program Planner",
  "Social Research",
  "Social Scientist",
  "Social Worker",
  "Sociologist",
  "Software Developer",
  "Software Engineer",
  "Software Test Engineer",
  "Software designer",
  "Soil Scientist",
  "Soldier",
  "Special Education Teacher",
  "Special Events Manager",
  "Special Projects Director",
  "Speech Pathologist",
  "Speech Writer",
  "Sports Event Manager",
  "Statistician",
  "Stockbroker",
  "Store Manager",
  "Strategic Alliance Director",
  "Strategic Planning Director",
  "Stress Reduction Specialist",
  "Stripper",
  "Structural Engineer",
  "Superintendent",
  "Supply Chain Director",
  "Surgeon",
  "Surveyor",
  "System Administrator",
  "System Engineer",
  "Systems Analyst",
  "Systems Programmer",
  "TV Programmer",
  "Tax Specialist",
  "Taxi driver",
  "Teacher",
  "Technical Illustrator",
  "Technical Support Specialist",
  "Technical Writer",
  "Technology Director",
  "Telecom Analyst",
  "Telemarketer",
  "Theatrical Director",
  "Title Examiner",
  "Tour Escort",
  "Tour Guide Director",
  "Tour guide",
  "Traffic Manager",
  "Trainer Translator",
  "Transportation Manager",
  "Travel Agent",
  "Travel agent",
  "Treasurer",
  "Truck driver",
  "Underwriter",
  "Union Representative",
  "University Administrator",
  "University Dean",
  "Urban Planner",
  "Vendor Relations Director",
  "Veterinarian",
  "Veterinary doctor",
  "Viticulturist",
  "Waiter",
  "Warehouse Manager",
  "Web designer",
  "Wildlife Specialist",
  "Zoologist",
];
